### ISSUE TITLE
(L) Investigate Memory Errors on Heroku

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#269]
Currently, we're getting tons of memory errors on Heroku: https://dashboard.heroku.com/apps/greencommons/metrics/web

In a 24 hour period, we saw 2.9k errors: https://cl.ly/3A193n3S4337

Looks like at its peak, the memory usage on the app jumps to ~1.8GB: https://cl.ly/2q2v3F2r2s0M

**Comment by ptrikutam** [comment]
Taking a deeper look, it seems like the issue resides primarily with the Homepage. We're loading something into memory that seems to choke up the server: https://cl.ly/2j2T00272d2y

The search page, surprisingly, is less than half the memory consumption increase.

**Comment by ptrikutam** [comment]
Further data: https://cl.ly/082I2f1N2a2s

I'm guessing the issue resides with the various calls we have to `Resource.sample` in [`StaticPagesController`](https://github.com/greencommons/commons/blob/master/app/controllers/static_pages_controller.rb#L7-L14).

This is the SQL query it seems to be generating:

```
SELECT "resources".* FROM "resources" WHERE "resources"."resource_type" = ?
```

**Comment by nsanta** [comment]
These are my findings:

- resources.resource_type does not have an index
- The query for fetch @networks includes users: if the networks fetched has several users, it will cause a significant memory allocation.
- The users association in Network model  is through networks_users table, and AR doesn't like eager loading the user, instead of, does a full scan table and fetch of networks_users and users.

I will be issuing a PR in the next minutes with proper fixes.
