### ISSUE TITLE
Searching for records either via the controller or model should return AR objects, not ES objects

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#44]

**Comment by adarsh** [comment]
From the [`elasticsearch-model`docs](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#search-results-as-database-records):

#### Search results as database records

Instead of returning documents from Elasticsearch, the `records` method will return a collection
of model instances, fetched from the primary database, ordered by score:

```ruby
response.records.to_a
# Article Load (0.3ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (1, 2)
# => [#<Article id: 1, title: "Quick brown fox">, #<Article id: 2, title: "Fast black dogs">]
```

The returned object is the genuine collection of model instances returned by your database,
i.e. `ActiveRecord::Relation` for ActiveRecord, or `Mongoid::Criteria` in case of MongoDB.

This allows you to chain other methods on top of search results, as you would normally do:

```ruby
response.records.where(title: 'Quick brown fox').to_a
# Article Load (0.2ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (1, 2) AND "articles"."title" = 'Quick brown fox'
# => [#<Article id: 1, title: "Quick brown fox">]

response.records.records.class
# => ActiveRecord::Relation::ActiveRecord_Relation_Article
```

The ordering of the records by score will be preserved, unless you explicitly specify a different
order in your model query language:

```ruby
response.records.order(:title).to_a
# Article Load (0.2ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (1, 2) ORDER BY "articles".title ASC
# => [#<Article id: 2, title: "Fast black dogs">, #<Article id: 1, title: "Quick brown fox">]
```

The `records` method returns the real instances of your model, which is useful when you want to access your
model methods -- at the expense of slowing down your application, of course.
In most cases, working with `results` coming from Elasticsearch is sufficient, and much faster. See the
[`elasticsearch-rails`](https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-rails)
library for more information about compatibility with the Ruby on Rails framework.

When you want to access both the database `records` and search `results`, use the `each_with_hit`
(or `map_with_hit`) iterator:

```ruby
response.records.each_with_hit { |record, hit| puts "* #{record.title}: #{hit._score}" }
# * Quick brown fox: 0.02250402
# * Fast black dogs: 0.02250402

**Comment by ptrikutam** [comment]
@adarsh cool -- curious what you think we should do? No change to the code, or add a `.records` to the retrieval of search results?

We may be making use of the score, so maybe it makes sense to keep things as ES search results for the time being?

**Comment by adarsh** [comment]
@ptrikutam I actually don't know. My first answer is "Return AR objects, that feels more natural" but I guess the answer to the "how much performance will this cost us?" question will be more apparent once we start to actually return results.

So :shrug_emoji:?

The score issue is moot, I believe because:

> Instead of returning documents from Elasticsearch, the `.records` method will return a collection
of model instances, fetched from the primary database, **ordered by score**.

**Comment by T-Dnzt** [comment]
@ptrikutam Finally, I went with `response.records.each_with_hit { |record, hit| puts "* #{record.title}: #{hit._score}" }` which returns AR objects (while also giving the score with the `hit` object). Maybe we can close this?

**Comment by ptrikutam** [comment]
Perfect, thanks.
