### ISSUE TITLE
Wrong ElasticSearch index name

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#97]
The following code in the `Resource` model might not be generating the index name we expect.

```ruby
class Resource < ApplicationRecord
  include Elasticsearch::Model
  index_name SearchIndex.index_name(self)
```

Since `self` here is the class, and given the following code in the `SearchIndex` class:

```ruby
  def self.index_name(record)
    "#{record.class.name.pluralize.downcase}-#{Rails.env}"
  end
```

We end up with the following index: `classes-development` (or `classes-production`).

Also, in the `reset_resource_index` rake task, we are still using the old index name instead of relying on the new method to generate it:

```ruby
namespace :elasticsearch do
  desc 'Deletes the "resource" index and regenerates it with all records currently in Resource'
  task reset_resource_index: :environment do
    client = Elasticsearch::Client.new(
      url: ENV.fetch('BONSAI_URL', 'http://localhost:9200'), log: true
    )
    client.indices.delete index: 'resources' # <--- HERE
    Resource.__elasticsearch__.create_index!
    Resource.import
  end
end
```

**Comment by ptrikutam** [comment]
Gotcha. Good catch. Strangely enough, the index seems to set up appropriately on my local machine.

@T-Dnzt Can you focus on this one first and try to debug?

**Comment by ptrikutam** [comment]
This one is very strange -- I'm getting the same problem on my machine when I try to reset the index.

Current theory: `self` on [this line](https://github.com/greencommons/commons/blob/master/app/models/resource.rb#L27) refers to the object instance itself. Therefore, in this place, using `.class.name.pluralize.downcase` (as is done in [SearchIndex](https://github.com/greencommons/commons/blob/master/app/service/search_index.rb#L3)) works fine. However, where [`self` is called to define the index_name itself](https://github.com/greencommons/commons/blob/master/app/models/resource.rb#L3), `self` returns `Resource`, the class. Therefore, doing `Resource.class` returns `Class` and that's why we end up with `classes-development`.

This should be fixable by changing [this line](https://github.com/greencommons/commons/blob/master/app/service/search_index.rb#L3) to:

```
 "#{record.name.pluralize.downcase}-#{Rails.env}"
```

Alternatively, we could pass an instantiated instance on [this line](https://github.com/greencommons/commons/blob/master/app/models/resource.rb#L3).

There's probably a few other solutions I'm not thinking of but hopefully this provides a good starting point.

Let me know if this helps!

**Comment by T-Dnzt** [comment]
Thanks! I went with the class name in this [PR](https://github.com/greencommons/commons/pull/100).

**Comment by T-Dnzt** [comment]
Currently running the import task without any issues. Closing this since the changes in PR #100 seem to be effective.
